# Generated by Django 2.2.3 on 2019-07-15 13:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=5)),
                ('intro', models.CharField(max_length=50)),
                ('shoperintro', models.CharField(max_length=50)),
                ('exintro', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='img')),
                ('img2', models.ImageField(upload_to='img')),
                ('img3', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='PollsUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Foods')),
            ],
        ),
    ]
