# Generated by Django 2.2.3 on 2019-07-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
