# Generated by Django 2.2.3 on 2019-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190716_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='price',
            new_name='price1',
        ),
        migrations.AddField(
            model_name='foods',
            name='price2',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
