# Generated by Django 2.2.3 on 2019-07-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190717_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='title',
        ),
    ]
