# Generated by Django 2.2.3 on 2019-07-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190717_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('foods', models.ManyToManyField(to='shop.Foods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PollsUser')),
            ],
        ),
    ]
