# Generated by Django 2.2.3 on 2019-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order1_order2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
