# Generated by Django 2.2.3 on 2019-07-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
