# Generated by Django 2.2.3 on 2019-07-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollsuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollsuser',
            old_name='telephone',
            new_name='telepone',
        ),
    ]
